### 几何建模
分析几何问题的方法：
 1. 传统几何的演绎-证明体系
 2. 基于向量的计算几何
 3. 基于极坐标与方程的解析几何

In [1]:
import numpy as np

#### 1.1 numpy.linalg 的使用


In [2]:
### 计算矩阵的逆
A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)
print("矩阵 A 的逆：\n", A_inv)

矩阵 A 的逆：
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [4]:
### 计算矩阵的特征值和特征向量
'''numpy.linalg.eig 用于计算方阵的特征值和特征向量'''
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

eigenvalues, eigenvectors = np.linalg.eig(A)
print("特征值：", eigenvalues)
print("特征向量：\n", eigenvectors)

特征值： [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
特征向量：
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [5]:
### 奇异值分解
'''numpy.linalg.svd  用于对矩阵进行奇异值分解'''
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

U, S, VT = np.linalg.svd(A)
print("U 矩阵：\n", U)
print("奇异值：", S)
print("VT 矩阵：\n", VT)

U 矩阵：
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
奇异值： [1.68481034e+01 1.06836951e+00 4.41842475e-16]
VT 矩阵：
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


#### 1.2 问题一

In [6]:
from scipy.optimize import fsolve

theta = 2 * np.pi / 3 
alpha = 1.5 / 180 * np.pi  
htheta = theta / 2  
h = 70  
d = 200  
k = np.tan(np.pi / 2 - htheta)
k0 = np.tan(alpha)


# 初始化
Aleft = []  # 左端点坐标
Aright = []  # 右端点坐标
Acenter = []   # 中心点坐标
W = [] # 覆盖宽度

for n in range(-4, 5):
    leftsolve = lambda t: k * (t - n * d) - k0 * t + h
    rightsolve = lambda t: -k * (t - n * d) - k0 * t + h
    tleft = fsolve(leftsolve, 0)
    tright = fsolve(rightsolve, 0)
    Aleft.append([tleft[0], k0 * tleft[0] - h])
    Aright.append([tright[0], k0 * tright[0] - h])
    Acenter.append([200 * n, k0 * 200 * n - h])
Aleft = np.array(Aleft)
Aright = np.array(Aright)
Acenter = np.array(Acenter)
D = Acenter[:, 1]  # 海水深度
W = np.sqrt((Aleft[:, 0] - Aright[:, 0]) ** 2 + (Aleft[:, 1] - Aright[:, 1]) ** 2)  # 覆盖宽度

# 计算重合部分
cover = np.zeros(8)
for i in range(8):
    cover[i] = np.sqrt((Aright[i, 0] - Aleft[i + 1, 0]) ** 2 + (Aright[i, 1] - Aleft[i + 1, 1]) ** 2)
eta = cover / W[1:]

d:\Anaconda3\envs\torch\lib\site-packages\scipy\optimize\minpack.py:175: RuntimeWarning: The iteration is not making good progress, as measured by the 
  improvement from the last ten iterations.
  warnings.warn(msg, RuntimeWarning)


In [8]:
print("海水深度 D: \n", -D)
print("覆盖宽度 W: \n", W)
print("重合部分比例 eta: \n", eta)

海水深度 D: 
 [90.94873726 85.71155294 80.47436863 75.23718431 70.         64.76281569
 59.52563137 54.28844706 49.05126274]
覆盖宽度 W: 
 [315.81332829 297.62756059 279.44179288 261.25602517 243.07025746
 224.88448975 206.69872205 188.51295434 170.32718663]
重合部分比例 eta: 
 [0.35695443 0.31510572 0.26743092 0.21262236 0.14894938 0.07407224
 0.01525164 0.12364966]
